channels:
    - pytorch
    - conda-forge
name:
    hpa-app
# pinned everything that is < 1.0, the rest is stable enough to not need pins
dependencies:
    - bioimageio.core >=0.5.5,<0.5.6
    - imageio
    - napari >=0.4.12,<0.4.13
    - numpy
    - pandas
    - requests
    - pytorch
    - scikit-image
    - scikit-learn
